### ISSUE TITLE
[REQUEST] / [ENHANCEMENT] Config for OctoPick ores

### ISSUE THREAD

**Issue by MsVoxxie** [owmii/Lost-Trinkets#101]
Hey there! I've noticed that the Octopick doesnt work with some modded ores, (Specifically Lib Vulpes)
I was wondering if we could possibly have the ability to add our own ores and such as a server(?) config to fix these issues when they arise, Otherwise, I suppose adding Vulpes support would work as well :)

**Comment by BlueAgent** [comment]
Octopick uses the `forge:ores` block tag.

Mods should add their ores to that block tag (and equivalent item tag too probably).

More specifically they should add their tag to the `forge:ores/<type>` tag, and then add that tag to `forge:ores`.

[Forge does something similar](https://github.com/MinecraftForge/MinecraftForge/blob/15d3df28187dc0439e17fa87384cfb4ea5c2803e/src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java#L80-L81) but adds the vanilla tag that includes stone and deepslate variants of coal, so the mod could also make their own tag to contain all variants of their ore if they want to do the same, but really as long as it's in `forge:ores` it should work with octopick.

Temporarily adding the ores to the tag manually with a datapack, crafttweaker, kubejs or similar would work too if you need it urgently.

**Comment by MsVoxxie** [comment]
> Octopick uses the `forge:ores` block tag.
> 
> Mods should add their ores to that block tag (and equivalent item tag too probably).
> 
> More specifically they should add their tag to the `forge:ores/<type>` tag, and then add that tag to `forge:ores`.
> 
> [Forge does something similar](https://github.com/MinecraftForge/MinecraftForge/blob/15d3df28187dc0439e17fa87384cfb4ea5c2803e/src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java#L80-L81) but adds the vanilla tag that includes stone and deepslate variants of coal, so the mod could also make their own tag to contain all variants of their ore if they want to do the same, but really as long as it's in `forge:ores` it should work with octopick.
> 
> Temporarily adding the ores to the tag manually with a datapack, crafttweaker, kubejs or similar would work too if you need it urgently.

Ahh I see, I actually glossed over the fact that Lib didn''t have this in the tag list, A datapack or otherwise will suit my needs, Appreciate the info! :)
