### ISSUE TITLE
[1.16.4] Octopus Legs cause crash after being hit by Wither Skeleton

### ISSUE THREAD

**Issue by NillerMedDild** [owmii/Lost-Trinkets#11]
Octopus Legs cause a crash after player is hit by Wither Skeleton.

### Crash report
https://gist.github.com/NillerMedDild/203134d8205d5a3ef2ecbc5d729c1f74

### Versions
- LostTrinkets-1.16.4-0.1.2
- Forge-1.16.4-35.1.7

**Comment by owmii** [comment]
Just tested on the client and server with wither skeletons and Wither boss too and is working fine, maybe there is some mod incompatibility that caused this crash.
Also, the crash report not saying anything about Lost Trinkets. :[

**Comment by NillerMedDild** [comment]
Dammit, right you are :P Can't reproduce with just Lost Trinkets, nor with Wither Skeleton Tweaks and Lost Trinkets.

**Comment by NillerMedDild** [comment]
Is there any way to disable the Octopus Trinket?

**Comment by owmii** [comment]
Changed how the code work to see if this will fix a the crash.

**Comment by owmii** [comment]
See V0.1.3

**Comment by NillerMedDild** [comment]
It took about 5 hits this time, but same issue I'm afraid. https://gist.github.com/NillerMedDild/8686acad9d18ffda45f23b1c6a15a56b

**Comment by owmii** [comment]
Now Octopus Leg has no functionality (temporarily) in v0.1.4, until I find a way to re-add it.

**Comment by NillerMedDild** [comment]
Thanks, I really appreciate it :)
