### ISSUE TITLE
[Suggestion] Tools and Weapons Mod Compat

### ISSUE THREAD

**Issue by Ridanisaurus** [owmii/Lost-Trinkets#18]
I noticed that using Tetra tools or weapons does not unlock Trinkets. Curious if it would be possible to introduce a tag system where as long as the Tool contains a specific tag it will count as a valid tool, and count toward the chances of unlocking trinkets. 

It feels punishing at the moment that I have to choose one mod over the other when doing my tasks around the base.

**Comment by BlueAgent** [comment]
I have been unlocking Trinkets using Tetra just fine. After looking into this more, it seems like there's a [2 minute cooldown between unlocking trinkets](https://github.com/owmii/Lost-Trinkets/blob/d822da25f743f4a68f9a56524318363962e527f7/src/main/java/owmii/losttrinkets/handler/UnlockManager.java#L68) that isn't configurable at the moment.

**Comment by BlueAgent** [comment]
Seems to be working okay in the latest version. Tested by setting the trinket unlock cooldown to zero and the killing trinket chance to `2`.

Was using the following mods:
jei-1.16.4-7.6.1.65
Lollipop-1.16.4-3.2.4
LostTrinkets-1.16.4-0.1.11
mgui-1.16.4-3.1.3
tetra-1.16.4-3.5.3

This can probably be closed now.
