### ISSUE TITLE
Crash with version 0.1.8

### ISSUE THREAD

**Issue by MathisSkate** [owmii/Lost-Trinkets#26]
Hello, i update to the new version !

That's crash, here is the log but no crash report ' https://hastebin.com/kipomohenu.csharp '

Thank you

**Comment by Coraline77447** [comment]
I've just ran into the same issue as you an hour later but using a different launcher... Guess we shall use 0.1.7 till owmii releases 0.1.9 that fixes this issue with it's mixin in 0.1.8... (Btw I was gonna report this same issue but you've beaten me to it an hour earlier.)

**Comment by owmii** [comment]
Crash report?
