### ISSUE TITLE
Are you officially willing to add another language?

### ISSUE THREAD

**Issue by chironader** [owmii/Lost-Trinkets#35]
I translated this mode into Korean (lang>json file)
Are you officially willing to add another language?

[ko_kr.zip](https://github.com/owmii/Lost-Trinkets/files/5837247/ko_kr.zip)

I'm so sorry if it was rude

Version was (LostTrinkets-1.16.4-0.1.11)

**Comment by owmii** [comment]
Thank you!! , I will add it in next version
