### ISSUE TITLE
[1.16.4] Lost trinkets with right click activations don't work

### ISSUE THREAD

**Issue by NillerMedDild** [owmii/Lost-Trinkets#36]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1014

> Multiple players reporting on my server that trinkets with right click activation (such as Magneto, which right clicks on air to get all items in a 10x10 range) do not work.

### Versions
- LostTrinkets-1.16.4-0.1.13
- Forge-1.16.4.35.1.37

**Comment by BlueAgent** [comment]
Right clicking effects currently require that you aren't looking at any block and your hand has to be empty (it is using the `PlayerInteractEvent.RightClickEmpty` clientside) and then the client sends a packet to the server to activate magneto.

**Comment by NillerMedDild** [comment]
My bad, thanks for the info :)
