### ISSUE TITLE
Latest Release does not work on 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [owmii/Lost-Trinkets#49]
Most 1.16.4 mods should work on 1.16.5 with the mods.toml updated to show it supports it

**Comment by BlueAgent** [comment]
Works fine using Lost Trinkets v0.1.18 (lollipop 3.2.4, mc 1.16.5 and forge 36.0.10) for me.
Maybe try the latest version? The past couple versions are bit broken (my fault).

**Comment by ModernGamingWorld** [comment]
@BlueAgent , its cause @owmii has not made this https://www.curseforge.com/minecraft/mc-mods/lost-trinkets/files/3184790 work with 1.16.5. They only have 1.16.4 support not 1.16.5, so it does not sync with 1.16.5

**Comment by BlueAgent** [comment]
Oh I see what you mean, so the file needs to be tagged that it does support 1.16.5 on CF, no changes to mods.toml needed.

**Comment by BlueAgent** [comment]
The file seems to be tagged with 1.16.5 now, is it working?
