### ISSUE TITLE
Mod crashing 

### ISSUE THREAD

**Issue by lacomarca** [owmii/Lost-Trinkets#5]
Hi,

I wanted to add your mod but it crashes as soon as I start the console. I tried to see if there was a problem with other mods, but I isolated yours and it's the one creating the conflict. I'm playing on a server and there is no crash report. I can only copy console info here.

Here some data from our server:

MC version: 1.16.3
Forge version: 34.1.19
Los trinkets version:LostTrinkets-1.16.3-0.1.2

Find below our report from console. Thanks a lot for your help!

26.10 11:22:19 [Multicraft] Loaded config for "Custom.jar (Use and upload your own JAR)"
26.10 11:22:19 [Multicraft] Updating eula.txt file
26.10 11:22:21 [Server] INFO 2020-10-26 11:22:21,359 main WARN Advanced terminal features are not available in this environment
26.10 11:22:21 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 34.1.19, --fml.mcpVersion, 20200911.084530, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, nogui]
26.10 11:22:21 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_265 by Private Build
26.10 11:22:21 [Server] main/INFO [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
26.10 11:22:21 [Server] main/INFO [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
26.10 11:22:24 [Server] main/INFO [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
26.10 11:22:24 [Server] main/INFO [mixin/]: Successfully loaded Mixin Connector [snownee.fruits.mixin.Connector]
26.10 11:22:24 [Server] main/INFO [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
26.10 11:22:24 [Server] main/INFO [Fruit Trees/]: Invoking Mixin Connector
26.10 11:22:24 [Server] main/ERROR [mixin/]: Mixin config assets/patchouli/patchouli.mixins.json does not specify "minVersion" property
26.10 11:22:24 [Server] main/INFO [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
26.10 11:22:24 [Server] main/WARN [mixin/]: Error loading class: net/minecraft/client/gui/screen/inventory/AnvilScreen (java.lang.ClassNotFoundException: null)
26.10 11:22:24 [Server] main/WARN [mixin/]: @Mixin target net.minecraft.client.gui.screen.inventory.AnvilScreen was not found anviltweaks.mixins.json:AnvilScreenMixin
26.10 11:22:24 [Server] INFO Starting Transform: ShetiPhianCore/recognise-thinner-blocks.js 'LivingEntity.playFallSound'
26.10 11:22:24 [Server] INFO Found injection point 'net/minecraft/entity/LivingEntity.func_226278_cu_' org.objectweb.asm.tree.MethodInsnNode@630390b9
26.10 11:22:24 [Server] INFO Instructions Injected
26.10 11:22:24 [Server] INFO Starting Transform: ShetiPhianCore/recognise-thinner-blocks.js 'Entity.getOnPosition'
26.10 11:22:24 [Server] INFO Found injection point 'net/minecraft/entity/Entity.field_233557_ao_' org.objectweb.asm.tree.FieldInsnNode@28a9494b
26.10 11:22:24 [Server] INFO Instructions Injected
26.10 11:22:24 [Server] INFO Starting Transform: ShetiPhianCore/recognise-thinner-blocks.js 'Entity.createRunningParticles'
26.10 11:22:24 [Server] INFO Found injection point 'net/minecraft/entity/Entity.func_226278_cu_' org.objectweb.asm.tree.MethodInsnNode@7d986d83
26.10 11:22:24 [Server] INFO Instructions Injected
26.10 11:22:26 [Server] main/WARN [mixin/]: Error loading class: owmii/lib/util/Stack (java.lang.ClassNotFoundException: null)
26.10 11:22:26 [Server] INFO Exception in thread "main" [11:22:26] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.reflect.Method.invoke(Method.java:498)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: ... 7 more
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97)
26.10 11:22:26 [Server] main/INFO [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
26.10 11:22:27 [Multicraft] Server shut down (starting)
26.10 11:22:27 [Multicraft] Not restarting crashed server.
26.10 11:22:27 [Multicraft] Looks like a crash, check the server console. Return value: 1
26.10 11:22:27 [Multicraft] Server stopped

**Comment by owmii** [comment]
It's clear that this is a `anviltweaks` bug trying to load a client class  from the server.
```
(java.lang.ClassNotFoundException: null)
26.10 11:22:24 [Server] main/WARN [mixin/]: @mixin target net.minecraft.client.gui.screen.inventory.AnvilScreen was not found anviltweaks.mixins.json:AnvilScreenMixin
```
