### ISSUE TITLE
Butcher's Cleaver doesn't seem to drop bones when used

### ISSUE THREAD

**Issue by VallenFrostweaver** [owmii/Lost-Trinkets#51]
Minecraft 1.16.5
Forge 36.0.10
Lost Trinkets 0.1.18
When equipping the Butcher's Cleaver in my Lost Trinket slot and killing several cows and sheep, no bones drop.

**Comment by BlueAgent** [comment]
Can't reproduce this bug.

It's a 10% drop chance so perhaps you just got really unlucky?

<details>
<summary>Screenshots</summary>

![2021-02-03_09 41 28](https://user-images.githubusercontent.com/630920/106685828-2dd88900-6604-11eb-9a2f-d76ce59fbef7.png)
![2021-02-03_09 41 31](https://user-images.githubusercontent.com/630920/106685850-37fa8780-6604-11eb-8f6b-5435443a9fea.png)
![2021-02-03_09 41 35](https://user-images.githubusercontent.com/630920/106685852-3a5ce180-6604-11eb-9f8a-e673bfab25a4.png)
</details>

**Comment by VallenFrostweaver** [comment]
I'll give it another go and report back.

**Comment by VallenFrostweaver** [comment]
UPDATE: I was mistaken and had poor results on my initial testing. My apologies for not being more thorough. Thanks also for adding a config option for a max trinket limit! <3
