### ISSUE TITLE
Balance config info thingy

### ISSUE THREAD

**Issue by Kutomi1** [owmii/Lost-Trinkets#58]
I literally set everything in the config file to the lowest chance possible, but if I'm actually doing things in the world, I get a trinket at least once every 5 minutes, and I think that's really OP. I really wish it was possible to make unlocking trinkets actually rare. And set a seperate config for unlocking trinkets of different rarities.

**Comment by BlueAgent** [comment]
What does your current config file look like could you please send it?

**Comment by Kutomi1** [comment]
OH, I SEE! I think I know what my problem was. I was big dumb and didn't read the config for drop chances carefully enough... I thought smaller number meant lower chance. I didn't quite understand why the minimum value was 2 and not 1, but now it all makes sense. Thanks a lot for the reply. I feel so stupid now.
