### ISSUE TITLE
Bug: Dragon's Breathe doesn't work.

### ISSUE THREAD

**Issue by Jusey1** [owmii/Lost-Trinkets#66]
Quick report on the Dragon's Breathe trinket which is suppose to auto-smelt blocks mined... It doesn't work. Not sure on what else to say about this issue in all honesty, ha-ha.

**Comment by nosevole** [comment]
Can confirm, dragon breath, glass shard and spider trinkets are currently not working.

**Comment by IamDuckyy** [comment]
Piggy also doesn't seem to work.

**Comment by Jusey1** [comment]
Piggy and Spider worked for me last I tried them out but they could've broke in recent update.

**Comment by owmii** [comment]
Fixed in `v0.1.27` Thanks for reporting!!
