### ISSUE TITLE
Horseshoe doesn't work

### ISSUE THREAD

**Issue by BasketBoyz** [owmii/Lost-Trinkets#84]
Horseshoe trinket doesn't make any effect on my character movement on 1.16.5. Mod version is 0.1.27 (Engimatica 6 modpack).

**Comment by DamonFyrian** [comment]
It also doesn't work in 0.5.4 of Enigmatic 6.

**Comment by Wlodek89** [comment]
Old version of enigmatica 6 works fine seen on YouTubers. Any one know what mod cause that issues?

**Comment by Mc-man165** [comment]
Im on 0.5.6 of the Enigmatica pack and it still doesnt seem to do anything. Mod version 0.1.27

**Comment by UltraHex** [comment]
Just updated from Enigmatica 6 0.4.14 to 0.5.9 and it stopped working.

**Comment by UltraHex** [comment]
Looks like a conflict with Yak Pants from the Environmental mod.

https://github.com/team-abnormals/environmental/commit/cb3a700faa352d10f9cfc60b2fc1aa9c99768fad

**Comment by DamonFyrian** [comment]
I wasn't using Yak Pants and never have and it still didn't work.

**Comment by UltraHex** [comment]
Yeah. So if you have Environmental 1.0.0 installed and  your not wearing Yak Pants, it disables step assist.

The solution is to update (or uninstall) Environmental.
